### ISSUE TITLE
Datos a nivel de parroquias

### ISSUE THREAD

**Issue by pabl-o-ce** [pablora19/COVID19_EC#13]
Según lei el gobierno quiere hacer esto recoleccion de datos por parroquias.
como podemos unir esa informacion.

yo igual hice mi recoleccion de datos:

[My Tracker](https://covid19ecuador.carreraestrada.com/)
[Data por provincias](https://carreraestrada-my.sharepoint.com/:x:/p/pcarrerae/ESzMCHkl6tJDvSx8ahkOZs8BcPv9RcHJIDWXfCu0d0Ic0g?e=tgqLuj)

El gobierno tiene por parroquias si podriamos trabajar para hacer esa recolleccion seria fascinante
[Gov Data](http://ecuador.analiticacovid.com/)

**Comment by georod** [comment]
Hola Pablo C.  Excelente tu Data Tracker (que tecnologías usaste?)
Ojo: el [mapa](https://ecuador.analiticacovid.com/) que creó el gobierno no está bien hecho. No se usa valores absolutos en mapas de ese tipo (choropleth).  Aquí se explica las razones y se dan tips: [choroplethmaps](https://blog.datawrapper.de/choroplethmaps/)   Suerte!

**Comment by pabl-o-ce** [comment]
Hola @georod react, typescript, D3.js (quiero usar mapbox para hacer el mapa por provincia, canton y parroquia pero recollectar esos datos esta muy complicado y quita mucho tiempo)

Si se el mapa es horrible pero lo unico bien que tienen son los datos por parroquias (eso vale oro).

Igual si quieres ayudarme en colaborar mi proyecto de [mi tracker esta abierto](https://github.com/pablocarreraest/covid19ecuador). **(cualquier buena idea es bien aceptada)**

Unos mexicanos ya estan haciendo algo similar para mexico con mi proyecto.

Y pues yo quiero agregar los datos de ecuador mas exactos a API's de terceros ya existentes
