### ISSUE TITLE
Valores en covid_ec.csv

### ISSUE THREAD

**Issue by georod** [pablora19/COVID19_EC#15]
Cuál es la relación de su archivo covid_ec.csv con este archivo [Google Sheets](https://docs.google.com/spreadsheets/d/1ZTXvIqq23cnmN-A8Fikyo6C_6jI3xYPE1Mff9fZOgHc/edit#gid=0)

Parecen ser similares. Gracias por la ayuda.

**Comment by pablora19** [comment]
son los mismos.
Lo hago porque hay personas que se les complica usar github
