### ISSUE TITLE
Invitación para integración de Dataset a nivel latinoamérica

### ISSUE THREAD

**Issue by pablodz** [pablora19/COVID19_EC#4]
Hola, junto con una organización sin fines de lucro se está tratando de centralizar la información de contagiados/muertos/recuperados covid-19 y estamos buscando un encargado por país. En tu caso Ecuador.

El formato del csv se está manejando acorde al formato global https://github.com/CSSEGISandData/COVID-19 para luego poder juntar la data.
Esto comprende las siguientes columnas:
![image](https://user-images.githubusercontent.com/28235457/77368025-6394bc00-6d29-11ea-9e53-da90978a510e.png)

Para tu país serían las siguientes filas, una actualización diaria:
![image](https://user-images.githubusercontent.com/28235457/77706568-c1770d00-6f90-11ea-8bd2-9038d50b2d63.png)

Podrías comentarme si estás interesado en aportar porfavor.
El dataset centralizado se propone en este repositorio: https://github.com/DataScienceResearchPeru/covid-19_latinoamerica
Se te puede dar acceso nivel `Maintainer` al repositorio mencionado, ya hay encargados de varios países.

**Comment by pablora19** [comment]
Dale acepto. 
Desde Todas las fechas ? Ec tiene registro de 13/03/2020.

**Comment by pablodz** [comment]
Creo que está actualizado hasta el 2020-03-21 de ahí en adelante seria o en todo caso revisar si coincide con los registros que posees y arreglar cualquier error correspondiente a EC. Te estoy dando acceso nivel `Mantainer` ahora mismo.

> Dale acepto.
> Desde Todas las fechas ? Ec tiene registro de 13/03/2020.
