### ISSUE TITLE
Datos de defunciones a nivel provincial y nacional

### ISSUE THREAD

**Issue by sbibauw** [pablora19/COVID19_EC#9]
Ayer, M.P. Romo publicó cifras de defunciones para los 3 primeros meses del 2020, comparados con los 2 años anteriores, y comparado entre las 9 zonas del Registro civil. Me parecen muy útil estos mismos datos para hacer análisis en el marco del COVID-19. Propongo crear un nuevo archivo aquí via un pull request. Le interesa o mejor lo pongo en un repo personal?

**Comment by sbibauw** [comment]
Si lo considera pertinente, puede aprobar el PR #10

**Comment by pablora19** [comment]
esta listo. Gracias
